# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XdVcb67NxtONqkLpw4yJuPbyIo3CVJ9y
"""

from print1 import print1
from print2 import print2

if __name__ == '__main__' :
  print1()
  print2()