# -*- coding: utf-8 -*-
"""print2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XdVcb67NxtONqkLpw4yJuPbyIo3CVJ9y
"""

def print2() :
  print('')